include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unnecessary_getters_setters: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
